// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNuOzMxLNMHVYFvQdn6ubQ_6YgM4qNNX0',
    appId: '1:700329710858:web:cf38f56039dd74519ad6f3',
    messagingSenderId: '700329710858',
    projectId: 'mobile-saturday',
    authDomain: 'mobile-saturday.firebaseapp.com',
    storageBucket: 'mobile-saturday.firebasestorage.app',
    measurementId: 'G-MBV2287V5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTi_uLkmKMHmDBjZJqNFe4DhrCn2aUFpQ',
    appId: '1:700329710858:android:356852f2469f5f689ad6f3',
    messagingSenderId: '700329710858',
    projectId: 'mobile-saturday',
    storageBucket: 'mobile-saturday.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6R8Bz8dJJUQtxazkQBZNH_IHbhLE14Rk',
    appId: '1:700329710858:ios:5131aa67d24342619ad6f3',
    messagingSenderId: '700329710858',
    projectId: 'mobile-saturday',
    storageBucket: 'mobile-saturday.firebasestorage.app',
    iosBundleId: 'campus-ah-moment.id.saturdayFirebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6R8Bz8dJJUQtxazkQBZNH_IHbhLE14Rk',
    appId: '1:700329710858:ios:5131aa67d24342619ad6f3',
    messagingSenderId: '700329710858',
    projectId: 'mobile-saturday',
    storageBucket: 'mobile-saturday.firebasestorage.app',
    iosBundleId: 'campus-ah-moment.id.saturdayFirebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNuOzMxLNMHVYFvQdn6ubQ_6YgM4qNNX0',
    appId: '1:700329710858:web:897f2325af71e0179ad6f3',
    messagingSenderId: '700329710858',
    projectId: 'mobile-saturday',
    authDomain: 'mobile-saturday.firebaseapp.com',
    storageBucket: 'mobile-saturday.firebasestorage.app',
    measurementId: 'G-C83HSF94VK',
  );
}
